development:
  jwt_secret_key: "pp98JsxQ86"
  db_password: nonoyako11

test:
  jwt_secret_key: "pp98JsxQ86"
  db_password: nonoyako11
  db_render_password: SU3AJDbEgV4R9hqsoFbLeqrX65Mh0IEf

production:
  jwt_secret_key: <%= ENV["pp98JsxQ86"] %>
  db_password: <%= ENV["nonoyako11"] %>
